Repository gdgphilippines/devfest2018, pull requests merged in 2018-09, with the labels that each got.

#6 Update master to meet with deployment
  .firebase/hosting.cHVibGlj.cache
  .firebaserc
  firebase.json
  frontend.config.js
  package-lock.json
  package.json
  src/assets/images/gdgph-3.png
  src/assets/images/sponsors/google.jpg
  src/components/footer-section/index.js
  src/components/footer-section/style.styl
  src/components/footer-section/template.js
  src/components/project-header/index.js
  src/components/project-header/template.js
  src/components/project-sidebar/index.js
  src/components/project-sidebar/template.js
  src/index.ejs
  src/pages/page-home/index.js
  src/pages/page-home/style.styl
  src/pages/page-home/template.js
  src/styles/general/limit-width.styl
Labels: review

#18 Fixed footer logo #11
  src/assets/images/gdgph-white.png
  src/components/footer-section/template.js
Labels: review

#19 fixed #9 and changed banner height for large screen
  src/pages/page-home/style.styl
  src/styles/general/typography.styl
Labels: aesthetics, review

#21 Fixed #20 Add badge on README.md
  .DS_Store
  README.md
Labels: review

#26 Added docs
  .gitignore
  docs/README.md
  docs/back-end/README.md
  docs/front-end/README.md
  docs/project-management/Commit.md
  docs/project-management/Forking-and-Branching.md
  docs/project-management/Installation.md
  docs/project-management/Project-Structure.md
  docs/project-management/Pull-Request.md
  docs/project-management/README.md
  docs/project-management/Running.md
  docs/project-management/Update-from-Develop.md
Labels: documentation, review

#25 Added Firebase Functions Fixed #23
  firebase.json
  functions/.eslintrc.json
  functions/README.md
  functions/index.js
  functions/package.json
Labels: functions, review

#39 Fixed #27 Add documentation on Forking and Branching
  docs/project-management/Forking-and-Branching.md
Labels: review

#40 Add environment, Connects #28
  .github/stale.yml
  delete.sh
  docs/README.md
  docs/project-management/Development-Environment.md
  package-lock.json
  package.json
Labels: documentation, review

#41 Fix #29 Add doc for commit rules
  docs/project-management/Commit.md
Labels: documentation, review

#42 Add documentation #17
  .DS_Store
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/README.md
  docs/front-end/Project-Structure.md
  docs/project-management/Commit.md
  docs/project-management/Development-Environment.md
  docs/project-management/Forking-and-Branching.md
  docs/project-management/Installation.md
  docs/project-management/Project-Structure.md
  docs/project-management/Pull-Request.md
  docs/project-management/README.md
  docs/project-management/Requirements.md
  docs/project-management/Review.md
  docs/project-management/Running.md
  docs/project-management/Update-from-Develop.md
  docs/project-management/images/issue.png
  docs/project-management/images/issues.png
Labels: review

#46 fix #10 change color to gray
  src/styles/general/color.styl
Labels: aesthetics, review

#47 fix #12 center footer and remove spacer in header
  src/components/footer-section/style.styl
  src/components/footer-section/template.js
  src/components/project-header/style.styl
  src/components/project-header/template.js
Labels: aesthetics, bug, review

#38 Added sample for https functions
  .firebaserc
  functions/https/actions/helloworld.js
  functions/https/base-express.js
  functions/https/models/user.js
  functions/index.js
  functions/package-lock.json
  functions/package.json
Labels: review
